### ISSUE TITLE
data file download script

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [reactome/container#22]
Need a script to download Reactome data files if they are not present.

**Comment by AyushyaChitransh** [comment]
I am working on this issue in branch [feature/downloadScript](https://github.com/reactome/container/tree/feature/downloadScript).

There were two possible approaches to update the file, using timestamping or using file-size. I am using file size since using default feature of `wget --timestampping` we were not able to resume partial downloads. Also timestamping cannot be used along with `--output-file`.
